// Regenerates ai-audit/AI_Audit_Report.md from the Claude Code session log.
// User prompts are copied VERBATIM from the log (never edited); timestamps are the log's own
// timestamps converted to UTC+7. AI-output lines are short factual summaries keyed by turn order.
// Adapted from HW04 automation/scripts/extract-audit.mjs.
// Usage: node ai-audit/extract-audit.mjs [path-to-session.jsonl]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const LOG =
  process.argv[2] ||
  'C:/Users/ADMIN/.claude/projects/D--23127249-QA-hw6/084beede-0a46-497a-8e4e-151b04d46541.jsonl';
const OUT = path.resolve(HERE, 'AI_Audit_Report.md');

// One short factual AI-output summary per genuine user turn, in order.
const AI = [
  'Acknowledged caveman ultra mode and held the terse style for the session (code/commits/security written normally).',
  'Read the HW06 spec + the four HW02 test-case files + the qa-skills; confirmed the 3 APIs (Profile FR-04 / Coupon FR-09 / Product CRUD FR-15), applied `ai-test-generation`, `api-testing`, `ci-cd-integration`, `ai-bug-triage`; read the SUT source (`server.js`/`database.js`) and live-verified the planted bugs; ran the staged pipeline to produce 127 test cases (42/42/43) with human audit + 5 extensions each; built the Postman collection generator + green/FAIL collections + env + data CSVs; ran Newman (41/41 green, 1 intentional fail = BUG-C1); wrote the bug report, GitHub Actions workflow, generator design + agent skill, Main report, AI audit, AI critique, README, git log, and MASTER-PLAN.',
  'Built a standalone repo (root = submission, CI paths adapted); made 10 per-step commits; `gh repo create --public 23127249-HW06-API-Testing` + push; triggered the green CI run, pushed a one-line COLLECTION flip for the red run, verified both (success + failure/exit-1), restored the green default, and filled the repo + run URLs into README/CI report/git log.',
  'Filed all 13 bugs as GitHub Issues (#1–#13) via `gh`; installed mermaid-cli and rendered `diagrams/generator.png` using the system Chrome; wrote a Puppeteer script (system Chrome, --no-sandbox) to screenshot the two CI runs and render the Newman `X-Student-Id: 23127249` console; corrected the bug count 12→13; committed and pushed all evidence.',
  'Gave the review checklist for a submission the student had not yet checked: verify Newman runs green locally, reproduce 3 bugs by curl, read the test-case docs for the oral defense, personalize the AI critique/audit, redraw the diagram (anti-cheat §11), and make the PDFs/zip.',
  'Wrote three study/hand-off docs — `TOOL-GUIDE.md` (every tool + a testing-concept glossary), `MY-TODO.md` (tickbox review + submit checklist), and `VIDEO-SCRIPT.md` (~6-min demo/defense script + Q&A prep); committed, pushed, and synced them into the zip-staging folder.',
  'Wrote this `ai-audit/extract-audit.mjs` (adapted from the HW04 extractor, additionally filtering `[Image:]` paste artifacts) and regenerated `AI_Audit_Report.md` with verbatim prompts + exact UTC+7 timestamps from the session log.',
];

const toICT = (iso) =>
  new Date(new Date(iso).getTime() + 7 * 3600 * 1000).toISOString().replace('T', ' ').slice(0, 16);

// Collect the genuine user prompts (verbatim) in order.
const turns = [];
for (const line of fs.readFileSync(LOG, 'utf8').split(/\r?\n/).filter(Boolean)) {
  let o;
  try { o = JSON.parse(line); } catch { continue; }
  if (o.type !== 'user' || !o.timestamp) continue;
  const c = o.message && o.message.content;
  let txt = '';
  if (typeof c === 'string') txt = c;
  else if (Array.isArray(c)) { const t = c.find((x) => x.type === 'text'); if (!t) continue; txt = t.text; }
  else continue;
  if (/tool_result|SYSTEM NOTIFICATION|task-notification|Request interrupted/.test(txt)) continue;
  const clean = txt
    .replace(/<command-message>[\s\S]*?<\/command-message>|<command-name>[\s\S]*?<\/command-name>|<command-args>[\s\S]*?<\/command-args>/g, '')
    .trim();
  if (!clean) continue;
  if (/^\[Image:/.test(clean)) continue; // screenshot-paste artifacts, not genuine prompts
  turns.push({ ts: toICT(o.timestamp), prompt: clean });
}

let md = `# AI Audit Report — HW06 API Testing on EShop

Student: **23127249** · APIs: **FR-04 Profile (Pool A) · FR-09 Coupon (Pool B) · FR-15 Product CRUD (Pool C)**
SUT: EShop \`eshop-sut\` (Backend :3000)

**Declaration:** *I use AI tools for the following tasks.*

# APPENDIX A: PROMPT LOG

## AI Tool Name: Claude (Claude Code — Opus 4.8, model id \`claude-opus-4-8\`)

User prompts are reproduced **verbatim** from the Claude Code session log. Timestamps are the log's
own timestamps, converted to **UTC+7**. Generated by \`ai-audit/extract-audit.mjs\`.
Session span: ${turns[0].ts} → ${turns[turns.length - 1].ts} (UTC+7). Genuine prompts: ${turns.length}
(screenshot-paste turns excluded).

---
`;

turns.forEach((t, idx) => {
  md += `
### Date and time: ${t.ts} (UTC+7)
### User:
${t.prompt}
### AI:
${AI[idx] || '(summary not recorded)'}

---
`;
});

md += `
## Tools declared
| Tool | Purpose |
|------|---------|
| Claude Code (\`claude-opus-4-8\`) | Staged test generation, collection scaffolding, reports, automation |
| Newman + newman-reporter-htmlextra | Test execution + HTML/JUnit reports |
| Postman collection format v2.1 | Test asset format |
| GitHub Actions + \`gh\` CLI | CI/CD pipeline, repo + Issues |
| @mermaid-js/mermaid-cli + Puppeteer (system Chrome) | Diagram render + evidence screenshots |
| qa-skills (ai-test-generation, api-testing, ci-cd-integration, ai-bug-triage) + custom eshop-api-test-generator | Method + reusable rule packs |

## Environment (reproducibility)
Node v22.20.0 · Newman 11.x · Windows 11 · SUT \`ttbhanh/eshop-sut@main\`, seeded via
\`backend/database.js\` · accounts \`test@eshop.com / Test1234!\`, \`admin@eshop.com / Admin123!\`.

## Anti-cheat note
The Newman \`X-Student-Id: 23127249\` console block, the \`localhost:3000\` hostname in the run
output, and the self-drawn generator diagram are real, attributable execution evidence — not
AI-generated. (Screenshots live in \`ci/screenshots/\`.)
`;

fs.writeFileSync(OUT, md, 'utf8');
console.log(`Wrote ${turns.length} verbatim prompts to ${OUT}`);
